import type { InioProfile } from "./types";

export const productDesignProfile: InioProfile = {
  id: "product-design",
  name: "Product Design",
  description:
    "Product design + AI-assisted coding: Discover, Build in src/, Verify, with TDD, E2E and logging-driven feedback loops.",
  localizedMeta: {
    zh: {
      name: "产品设计 + AI 实现",
      description:
        "产品设计 + AI 辅助编码落地：Discover（调研+设计合并）→ Build（在 src/ 实现）→ Verify（验收）；默认推荐 TDD，要求覆盖单元测试与 E2E，并通过完整日志建立反馈闭环，不限于「只做设计稿」。"
    }
  },
  extends: "core",
  requiredDirs: ["workflow/01-discover", "workflow/02-build", "workflow/03-verify"],
  requiredFiles: [
    "workflow/01-discover/README.md",
    "workflow/01-discover/problem-statement.md",
    "workflow/01-discover/competitor-scan.md",
    "workflow/01-discover/context-questions.md",
    "workflow/01-discover/product-stage-decision.md",
    "workflow/01-discover/prd.md",
    "workflow/01-discover/user-journey.md",
    "workflow/02-build/README.md",
    "workflow/02-build/01plan.md",
    "workflow/02-build/testing-plan.md",
    "workflow/02-build/logging-plan.md",
    "workflow/03-verify/README.md",
    "workflow/03-verify/usability-checklist.md",
    "workflow/03-verify/test-evidence.md",
    "workflow/03-verify/feedback-loop.md"
  ],
  files: {
    "workflow/01-discover/README.md": [
      "# 01-discover",
      "",
      "Capture research insights and define product solution in one stage."
    ].join("\n"),
    "workflow/01-discover/problem-statement.md": [
      "# Problem Statement",
      "",
      "## Target User",
      "-",
      "",
      "## Core Problem",
      "-",
      "",
      "## Why Now",
      "-"
    ].join("\n"),
    "workflow/01-discover/competitor-scan.md": [
      "# Competitor Scan",
      "",
      "| Product | Strength | Weakness | Opportunity |",
      "| --- | --- | --- | --- |",
      "| | | | |"
    ].join("\n"),
    "workflow/01-discover/context-questions.md": [
      "# Context Questions",
      "",
      "Use this file to drive active discussion with stakeholders/users before building.",
      "",
      "## Business Context",
      "- What business goal does this feature support?",
      "- What is the expected impact metric?",
      "",
      "## User Context",
      "- Who is the primary user and what is their current workflow?",
      "- What is the highest-friction step today?",
      "",
      "## Constraint Context",
      "- Deadline and release constraints",
      "- Technical/system constraints",
      "- Compliance/privacy constraints",
      "",
      "## Confirmation Notes",
      "- Open questions:",
      "- Confirmed assumptions:",
      "- Rejected directions:"
    ].join("\n"),
    "workflow/01-discover/product-stage-decision.md": [
      "# Product Stage Decision",
      "",
      "Decide whether this iteration targets MVP, growth stage, or end-state architecture.",
      "",
      "## Candidate Stages",
      "- MVP: fastest validated path with minimal scope",
      "- Growth: scalable implementation for near-term expansion",
      "- End-state: long-term architecture and full capability",
      "",
      "## Decision",
      "- Selected stage:",
      "- Why:",
      "- What we intentionally defer:",
      "",
      "## Scope Guardrails",
      "- Must-have:",
      "- Should-have:",
      "- Won't-have (this iteration):"
    ].join("\n"),
    "workflow/01-discover/prd.md": [
      "# PRD",
      "",
      "## Goal",
      "-",
      "",
      "## Scope",
      "- In scope",
      "- Out of scope",
      "",
      "## Functional Requirements",
      "1.",
      "",
      "## Non-functional Requirements",
      "-",
      "",
      "## Metrics",
      "-"
    ].join("\n"),
    "workflow/01-discover/user-journey.md": [
      "# User Journey",
      "",
      "| Step | User Goal | Product Response | Risk |",
      "| --- | --- | --- | --- |",
      "| | | | |"
    ].join("\n"),
    "workflow/02-build/README.md": [
      "# 02-build",
      "",
      "Plan implementation milestones and execution steps."
    ].join("\n"),
    "workflow/02-build/01plan.md": [
      "# Build Plan 01",
      "",
      "## Milestone",
      "-",
      "",
      "## Checklist",
      "- [ ]",
      "",
      "## Definition of Done",
      "-"
    ].join("\n"),
    "workflow/02-build/testing-plan.md": [
      "# Testing Plan",
      "",
      "Keep test strategy explicit from day 1.",
      "",
      "## Unit Test Scope",
      "- Core business rules and edge-case decision logic",
      "- Utility/pure functions",
      "- State transition logic",
      "",
      "## E2E Test Scope",
      "- Primary user journey (happy path)",
      "- Critical failure/recovery path",
      "- Permission and role variants (if applicable)",
      "",
      "## Test Matrix",
      "| Scenario | Unit | E2E | Owner |",
      "| --- | --- | --- | --- |",
      "| | [ ] | [ ] | |",
      "",
      "## Gate",
      "- No release if critical unit tests fail",
      "- No release if key journey E2E fails"
    ].join("\n"),
    "workflow/02-build/logging-plan.md": [
      "# Logging Plan",
      "",
      "Design logs for diagnosis, not noise.",
      "",
      "## Event Schema",
      "| Event Name | Trigger | Required Fields |",
      "| --- | --- | --- |",
      "| | | traceId, userId/sessionId, feature, action, result, latencyMs, errorCode |",
      "",
      "## Logging Levels",
      "- INFO: key business flow checkpoints",
      "- WARN: recoverable anomalies",
      "- ERROR: failed operations with root-cause context",
      "",
      "## Rules",
      "- Every request chain carries traceId.",
      "- Avoid sensitive data in logs.",
      "- Include input summary + output summary + error context for critical paths."
    ].join("\n"),
    "workflow/03-verify/README.md": [
      "# 03-verify",
      "",
      "Track validation notes, usability checks and acceptance results."
    ].join("\n"),
    "workflow/03-verify/usability-checklist.md": [
      "# Usability Checklist",
      "",
      "- [ ] Core task can be completed in < 3 minutes",
      "- [ ] Empty state provides clear next step",
      "- [ ] Error states are understandable",
      "- [ ] Copy is clear and action-oriented"
    ].join("\n"),
    "workflow/03-verify/test-evidence.md": [
      "# Test Evidence",
      "",
      "Record test outputs and links for release review.",
      "",
      "## Unit Test Evidence",
      "- Command:",
      "- Result summary:",
      "- Failing tests and resolution notes:",
      "",
      "## E2E Test Evidence",
      "- Command:",
      "- Environments/browsers:",
      "- Report/trace links:",
      "",
      "## Regression Notes",
      "- What changed since last iteration:",
      "- Re-validated critical paths:"
    ].join("\n"),
    "workflow/03-verify/feedback-loop.md": [
      "# Feedback Loop",
      "",
      "Use logs, test evidence, and user feedback to shorten debug and iteration cycles.",
      "",
      "## Inputs",
      "- Production/runtime logs",
      "- Unit/E2E failures",
      "- User feedback and support tickets",
      "",
      "## Loop",
      "1. Detect signal (error, friction, failure trend)",
      "2. Locate root cause with trace + test evidence",
      "3. Patch + add/strengthen tests",
      "4. Validate and document learnings",
      "",
      "## Output",
      "- Root-cause summary",
      "- Permanent fix",
      "- New guardrail (test/log/alert)"
    ].join("\n")
  },
  localizedFiles: {
    zh: {
      "workflow/01-discover/README.md": [
        "# 01-discover",
        "",
        "在同一阶段完成调研洞察与方案定义。"
      ].join("\n"),
      "workflow/01-discover/problem-statement.md": [
        "# 问题定义",
        "",
        "## 目标用户",
        "-",
        "",
        "## 核心问题",
        "-",
        "",
        "## 为什么现在要解决",
        "-"
      ].join("\n"),
      "workflow/01-discover/competitor-scan.md": [
        "# 竞品扫描",
        "",
        "| 产品 | 优势 | 劣势 | 机会点 |",
        "| --- | --- | --- | --- |",
        "| | | | |"
      ].join("\n"),
      "workflow/01-discover/context-questions.md": [
        "# 上下文澄清问题清单",
        "",
        "在开始实现前，用这份清单与用户/干系人进行主动讨论。",
        "",
        "## 业务上下文",
        "- 这个需求服务的业务目标是什么？",
        "- 最关键的结果指标是什么？",
        "",
        "## 用户上下文",
        "- 核心用户是谁，当前路径是什么？",
        "- 目前最痛的环节在哪里？",
        "",
        "## 约束上下文",
        "- 时间与上线窗口约束",
        "- 技术与系统约束",
        "- 合规与隐私约束",
        "",
        "## 确认记录",
        "- 待确认问题：",
        "- 已确认假设：",
        "- 本轮不做："
      ].join("\n"),
      "workflow/01-discover/product-stage-decision.md": [
        "# 产品阶段决策",
        "",
        "明确本轮是做 MVP、增长期方案，还是终态架构，避免目标漂移。",
        "",
        "## 可选阶段",
        "- MVP：最小范围、最快验证",
        "- 增长期：兼顾质量与扩展性",
        "- 终态：面向长期能力与架构",
        "",
        "## 决策",
        "- 选择阶段：",
        "- 选择原因：",
        "- 明确延后项：",
        "",
        "## 范围护栏",
        "- 必须做：",
        "- 应该做：",
        "- 本轮不做："
      ].join("\n"),
      "workflow/01-discover/prd.md": [
        "# PRD",
        "",
        "## 目标",
        "-",
        "",
        "## 范围",
        "- 范围内",
        "- 范围外",
        "",
        "## 功能需求",
        "1.",
        "",
        "## 非功能需求",
        "-",
        "",
        "## 指标",
        "-"
      ].join("\n"),
      "workflow/01-discover/user-journey.md": [
        "# 用户旅程",
        "",
        "| 步骤 | 用户目标 | 产品响应 | 风险 |",
        "| --- | --- | --- | --- |",
        "| | | | |"
      ].join("\n"),
      "workflow/02-build/README.md": [
        "# 02-build",
        "",
        "定义构建阶段的里程碑、任务与落地步骤。"
      ].join("\n"),
      "workflow/02-build/01plan.md": [
        "# 第 01 次构建计划",
        "",
        "## 里程碑",
        "-",
        "",
        "## 检查项",
        "- [ ]",
        "",
        "## 完成定义（DoD）",
        "-"
      ].join("\n"),
      "workflow/02-build/testing-plan.md": [
        "# 测试计划",
        "",
        "从第一天就把测试策略写清楚。",
        "",
        "## 单元测试范围",
        "- 核心业务规则与边界分支",
        "- 工具函数/纯函数",
        "- 关键状态流转逻辑",
        "",
        "## E2E 测试范围",
        "- 主路径（快乐路径）",
        "- 关键失败与恢复路径",
        "- 权限/角色差异场景（如适用）",
        "",
        "## 测试矩阵",
        "| 场景 | 单元 | E2E | 负责人 |",
        "| --- | --- | --- | --- |",
        "| | [ ] | [ ] | |",
        "",
        "## 发布门禁",
        "- 关键单测失败不允许发布",
        "- 关键路径 E2E 失败不允许发布"
      ].join("\n"),
      "workflow/02-build/logging-plan.md": [
        "# 日志策略",
        "",
        "日志的目标是快速定位问题，而不是堆日志量。",
        "",
        "## 事件结构",
        "| 事件名 | 触发条件 | 必填字段 |",
        "| --- | --- | --- |",
        "| | | traceId, userId/sessionId, feature, action, result, latencyMs, errorCode |",
        "",
        "## 日志级别",
        "- INFO：关键业务流节点",
        "- WARN：可恢复异常",
        "- ERROR：失败操作与根因上下文",
        "",
        "## 规则",
        "- 全链路必须携带 traceId。",
        "- 禁止记录敏感信息。",
        "- 关键路径记录输入摘要 + 输出摘要 + 错误上下文。"
      ].join("\n"),
      "workflow/03-verify/README.md": [
        "# 03-verify",
        "",
        "记录验收说明、可用性验证与测试结果。"
      ].join("\n"),
      "workflow/03-verify/usability-checklist.md": [
        "# 可用性检查清单",
        "",
        "- [ ] 核心任务可在 3 分钟内完成",
        "- [ ] 空状态提供明确下一步",
        "- [ ] 错误提示可理解、可操作",
        "- [ ] 文案清晰且面向行动"
      ].join("\n"),
      "workflow/03-verify/test-evidence.md": [
        "# 测试证据记录",
        "",
        "记录发布前测试证据与结论。",
        "",
        "## 单元测试证据",
        "- 执行命令：",
        "- 结果摘要：",
        "- 失败用例与修复说明：",
        "",
        "## E2E 测试证据",
        "- 执行命令：",
        "- 环境/浏览器：",
        "- 报告/trace 链接：",
        "",
        "## 回归说明",
        "- 相比上次迭代变更点：",
        "- 已回归验证的关键路径："
      ].join("\n"),
      "workflow/03-verify/feedback-loop.md": [
        "# 反馈闭环",
        "",
        "用日志 + 测试证据 + 用户反馈，缩短定位与修复周期。",
        "",
        "## 输入",
        "- 运行日志",
        "- 单测/E2E 失败信息",
        "- 用户反馈与工单",
        "",
        "## 闭环步骤",
        "1. 发现信号（错误、阻塞、失败趋势）",
        "2. 借助 trace 与测试证据定位根因",
        "3. 修复并补齐/强化测试",
        "4. 再验证并沉淀经验",
        "",
        "## 产出",
        "- 根因说明",
        "- 永久性修复",
        "- 新护栏（测试/日志/告警）"
      ].join("\n")
    }
  }
};
